[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_app = "6oxtWzqY9xAZsx8MNiibA8yqddHE4Pt1KAUwtDtkjs1g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
